markdown: kramdown
title: Using Word to write an accessible mathematical document
email: mash-access@bath.ac.uk
theme: jekyll-theme-cayman
show_downloads: true

markdown: kramdown  
kramdown:
  math_engine: mathjax  
  math_engine_opts:
    preview: true   